spring:
  profiles:
    # 定义你自己的application-db.yml
    # 以此来引用如mysql-driver-class-name之类的变量
    active: db
  datasource:
    driver-class-name: ${mysql-driver-class-name}
    url: ${mysql-url}
    username: ${mysql-username}
    password: ${mysql-password}
  quartz:
    job-store-type: jdbc
    properties:
      jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        tablePrefix: QRTZ_
        useProperties: false
      threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 10
        threadPriority: 5